config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :about
  resources :posts do
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  root to: "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_rich_text :content
  has_many_attached :images
  validates :title, :presence => true
  validates :content, :presence => true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.comments.destroy_all
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully removed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:content, :title, :images)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <label class="label">Title</label>
    <div class="control">
      <%= form.text_field :title, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :body, class: "label" %>
    <div class="control" style="min-height:13em;">
      <%= form.rich_text_area :content %>
    </div>
  </div>

  <div>
    <%= form.submit class: "button is-success mb-2" %>
  </div>

  <% end %>
</div>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <div class="container mb-2"><h2 class="title">
    <%= post.title %></h2>
  </div>
  <article class="media">
    <figure class="media-left">
      <p class="image is-64x64">
          <% avatar = User.find(post.author_id).avatar %>
          <% if avatar.attached? %>
            <%= image_tag avatar %>
          <% else %>
            <%= image_tag('/profile_placeholer.png') %> 
          <% end %>
      </p>
    </figure>
      <div class="content mb-3">
        <span class="is-size-5 has-text-weight-semibold"><p>Written by: <span class="has-text-weight-semibold has-text-success"><%= User.find(post.author_id).name %></span></p></span>
        <p class="is-size-7"><span id='post-time-<%= post.id %>'></span></p>
        <script>
            var postTime = new Date('<%= post.created_at.iso8601%>');
            var timestampItem = document.querySelector("#post-time-<%= post.id %>");
            timestampItem.innerHTML = postTime.toLocaleString('en-US');
        </script>
        <div class="container mb-5 mt-5">
          <%= post.content %>
        </div>
      </div>
  </article>
</div>

app/views/posts/edit.html.erb
<h1 class="title has-text-success">Edit post</h1>

<div class="container">
<%= render "form", post: @post %>

  <div>
    <%= link_to "Show this post", @post %> |
    <%= link_to "Back to posts", posts_path %>
  </div>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<div class=container>
  <% @posts.each do |post| %>
    <%= render post %>
 
      <%= link_to "Show this post", post, class: "button is-success mt-1" %>
<hr>
  <% end %>
</div>
<% if current_user != nil %>
  <% if current_user.email == "fjohnette@pm.me" %>
    <%= link_to "New post", new_post_path, class: "button is-primary mt-1" %>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<h1 class="title has-text-success">New post</h1>
<div class="contanier">
<%= render "form", post: @post %>
  <div>
    <%= link_to "Back to home", posts_path %>
  </div>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="post mb-0">
  <%= render @post %>
</div>
<% if current_user != nil %>
  <% if current_user.email == "fjohnette@pm.me" %>
    <%= button_to "Delete", @post, method: :delete, class: "button is-small is-danger is-inverted mt-1" %>
    <%= link_to " Edit post", edit_post_path(@post), class: "button is-small is-success is-inverted mt-1" %>
  <% end %>
<% end %>  
<div class="comments container pt-0">
  <hr>
  <% if current_user %>
  <div class="comment create">
    <h2 class="subtitle has-text-weight-semibold has-text-success">Leave a comment</h2>
  
    <%= render "comments/form", comment: @post.comments.new, the_url: post_comments_path(@post) %>
  </div>
  <% else %>
  <h2 class="subtitle has-text-weight-semibold has-text-success"><a href="/users/sign_in" class="has-text-success">Log in</a> to leave a comment</h2>
  <% end %>
  <div class="comment-list container mt-5">
    <h2 class="subtitle has-text-weight-bold"><%= pluralize(@post.comments.count, "Comment") %> </h2>
    <% @post.comments.where("id > 0").each do |comment| %>

    <article class="media">
      <figure class="media-left">
        <p class="image is-64x64">
          <% avatar = User.find(comment.author_id).avatar %>
          <% if avatar.attached? %>
            <%= image_tag avatar %>
          <% else %>
            <%= image_tag('/profile_placeholer.png') %> 
          <% end %>
          <% if current_user != nil %>
            <% if current_user.id == comment.author_id %>
              <%= button_to "Delete", post_comment_path(@post, comment), method: :delete, class: "button is-small is-danger is-inverted mt-1" %>
              <%= link_to "Edit", edit_post_comment_path(@post, comment), class: "button is-small is-success is-inverted mt-1" %>
            <% end %>
          <% end %>
        </p>
      </figure>
      <div class="content mb-2">
        <span class="is-size-5 has-text-weight-semibold"><p class="has-text-weight-semibold has-text-success"><%= User.find(comment.author_id).name %></p></span>
        <p class="is-size-7"><span id='comment-time-<%= comment.id %>'></span></p>
        <script>
            var commentTime = new Date('<%= comment.created_at.iso8601%>');
            var timestampItem = document.querySelector("#comment-time-<%= comment.id %>");
            timestampItem.innerHTML = commentTime.toLocaleString('en-US');
        </script>
        <div class="container mt-2">
          <%= comment.content %>
        </div>

      </div>
    </article>
  <% end %>
  </div>
</div>